### ISSUE TITLE
Image dump

### ISSUE THREAD

**Issue by SolarLune** [SolarLune/resolv#2]
![multishapestest2](https://user-images.githubusercontent.com/4733521/47263447-bde77880-d4b6-11e8-8472-b68ffe114bc9.gif)

![smoove](https://user-images.githubusercontent.com/4733521/47263453-bfb13c00-d4b6-11e8-9b3a-6b2c6afa1b6a.gif)

![peek 2018-09-15 02-26](https://user-images.githubusercontent.com/4733521/45585063-0c3fa100-b893-11e8-93df-7a14be9992ae.gif)

![resolv_3_updated](https://user-images.githubusercontent.com/4733521/45698619-48863200-bb1d-11e8-8fab-f1f359fea8b3.gif)

![softcollision](https://user-images.githubusercontent.com/4733521/45914938-0a309180-be01-11e8-8a1a-6efc8fe9203b.png)

![2015-03-29-soft-collision](https://user-images.githubusercontent.com/4733521/45914977-b5d9e180-be01-11e8-8096-18417642e80c.gif)

![intersectiontests](https://user-images.githubusercontent.com/4733521/51143628-ce806400-1803-11e9-93b0-2c7a3a78f282.gif)

**Comment by refacto** [comment]
Hi, this looks awesome :) Would you mind sharing the source code of the last example, if it's no hassle to you?

**Comment by einthusan** [comment]
are these bugs or .. ? why is it opened as an issue with no description?

**Comment by SolarLune** [comment]
These aren't bugs, this is an image dump (an issue that hosts the images for reference in other issues). In retrospect, this isn't necessary anymore, I believe, as you can simply drag images onto issues to attach them / upload them.
