### ISSUE TITLE
Example rendered by Ebiten, and compiled to WebAssembly

### ISSUE THREAD

**Issue by peterhellberg** [SolarLune/resolv#5]
I wrote a version of the resolv example using [Ebiten](https://github.com/hajimehoshi/ebiten): https://gist.github.com/peterhellberg/c8b61e9efc73c2c9eeae26c7cef207e8

<img width="640" alt="resolv-example" src="https://user-images.githubusercontent.com/565124/46320055-ceee4980-c5dc-11e8-9698-e4a268931e3d.png">

And then I compiled it to WebAssembly using [wasmgo](https://github.com/dave/wasmgo) (which also deploys to jsgo.io): https://jsgo.io/9e575f464c9bdc76db833f4160b646dc007d25f6

Feel free to copy my code if you like it.

**Comment by SolarLune** [comment]
Wow, this is cool. Excellent work, man! I don't know about copying the code itself, but I can definitely link to it on the Readme, along with the demo itself.

**Comment by peterhellberg** [comment]
Yes, I just wanted to try out your package :)

**Comment by peterhellberg** [comment]
(For examples of resolv usage I suggest using a separate repo, in order to not bloat the package repo)
