### ISSUE TITLE
Point line intersection

### ISSUE THREAD

**Issue by kyeett** [SolarLune/resolv#6]
Hi! 

I discovered this package yesterday and like it a lot. 

Would it be possible to get the point of intersection between lines? I've been working on ray casting to cast shadows, and currently use github.com/paulmach/go.geo, but it would be great if resolv could support it.

Example here: https://jsgo.io/kyeett/2d-vision

**Comment by SolarLune** [comment]
Hello! Thanks for checking Resolv out!

As it turns out, the code to do line collision checking seems to be almost 100% of the code to return the intersection point, haha. So it shouldn't be too hard to make a function to do this - I'll see about this soon.

**Comment by kyeett** [comment]
Great! Appreciate your work. 

I had to do a small implementation, for a more selfcontained demo, for ebiten. Can be used for reference, if you want.

```
// intersection calculates the intersection of given two lines.
// https://en.wikipedia.org/wiki/Line%E2%80%93line_intersection#Given_two_points_on_each_line
func intersection(l1, l2 Line) (float64, float64, error) {
	denom := (l1.X1-l1.X2)*(l2.Y1-l2.Y2) - (l1.Y1-l1.Y2)*(l2.X1-l2.X2)
	tNum := (l1.X1-l2.X1)*(l2.Y1-l2.Y2) - (l1.Y1-l2.Y1)*(l2.X1-l2.X2)
	uNum := -((l1.X1-l1.X2)*(l1.Y1-l2.Y1) - (l1.Y1-l1.Y2)*(l1.X1-l2.X1))

	if denom == 0 {
		return 0, 0, errors.New("lines parallel or coincident")
	}

	t := tNum / denom
	if t > 1 || t < 0 {
		return 0, 0, errors.New("lines intersect, segments do not")
	}

	u := uNum / denom
	if u > 1 || u < 0 {
		return 0, 0, errors.New("lines intersect, segments do not")
	}

	x := l1.X1 + t*(l1.X2-l1.X1)
	y := l1.Y1 + t*(l1.Y2-l1.Y1)
	return x, y, nil
}
```

https://hajimehoshi.github.io/ebiten/examples/raycasting.html

**Comment by SolarLune** [comment]
Yo, it's been implemented! Thanks for the examples!

**Comment by kyeett** [comment]
Thanks :-) Looks good!
