### ISSUE TITLE
How is the performance?

### ISSUE THREAD

**Issue by einthusan** [SolarLune/resolv#8]
You said your using "fmt" and "math" packages. The "fmt" package is notoriously slow, what are you using it for?

Maybe you can run some performance metrics to show how many rectangles you can a make and have collision testing and resolution for at 60 fps? ... to being with.

**Comment by SolarLune** [comment]
Hello; very sorry for the late reply, but while I don't have performance metrics, I no longer use `fmt` (it was just for printing out errors). I could still stand to include some performance metrics, though.
